// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        string             `db:"id" json:"id"`
	ProjectID string             `db:"project_id" json:"project_id"`
	Key       string             `db:"key" json:"key"`
	Name      pgtype.Text        `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Dataset struct {
	ID          string             `db:"id" json:"id"`
	ProjectID   string             `db:"project_id" json:"project_id"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type DatasetItem struct {
	ID             string             `db:"id" json:"id"`
	DatasetID      string             `db:"dataset_id" json:"dataset_id"`
	Input          []byte             `db:"input" json:"input"`
	ExpectedOutput []byte             `db:"expected_output" json:"expected_output"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	SourceTraceID  pgtype.Text        `db:"source_trace_id" json:"source_trace_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type DatasetRun struct {
	ID        string             `db:"id" json:"id"`
	DatasetID string             `db:"dataset_id" json:"dataset_id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type DatasetRunItem struct {
	ID            string             `db:"id" json:"id"`
	DatasetRunID  string             `db:"dataset_run_id" json:"dataset_run_id"`
	DatasetItemID string             `db:"dataset_item_id" json:"dataset_item_id"`
	ObservationID pgtype.Text        `db:"observation_id" json:"observation_id"`
	ScoreID       pgtype.Text        `db:"score_id" json:"score_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Member struct {
	ID     string `db:"id" json:"id"`
	UserID string `db:"user_id" json:"user_id"`
	OrgID  string `db:"org_id" json:"org_id"`
	Role   string `db:"role" json:"role"`
}

type Observation struct {
	ID                  string             `db:"id" json:"id"`
	TraceID             string             `db:"trace_id" json:"trace_id"`
	Type                string             `db:"type" json:"type"`
	Name                pgtype.Text        `db:"name" json:"name"`
	Input               []byte             `db:"input" json:"input"`
	Output              []byte             `db:"output" json:"output"`
	Metadata            []byte             `db:"metadata" json:"metadata"`
	Model               pgtype.Text        `db:"model" json:"model"`
	ModelParameters     []byte             `db:"model_parameters" json:"model_parameters"`
	StartTime           pgtype.Timestamptz `db:"start_time" json:"start_time"`
	EndTime             pgtype.Timestamptz `db:"end_time" json:"end_time"`
	TokenUsage          []byte             `db:"token_usage" json:"token_usage"`
	Cost                pgtype.Float8      `db:"cost" json:"cost"`
	Status              string             `db:"status" json:"status"`
	ParentObservationID pgtype.Text        `db:"parent_observation_id" json:"parent_observation_id"`
}

type Organization struct {
	ID        string             `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Project struct {
	ID        string             `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	OrgID     string             `db:"org_id" json:"org_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Prompt struct {
	ID        string             `db:"id" json:"id"`
	ProjectID string             `db:"project_id" json:"project_id"`
	Name      string             `db:"name" json:"name"`
	Version   int32              `db:"version" json:"version"`
	Prompt    []byte             `db:"prompt" json:"prompt"`
	Config    []byte             `db:"config" json:"config"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Score struct {
	ID        string             `db:"id" json:"id"`
	TraceID   string             `db:"trace_id" json:"trace_id"`
	Name      string             `db:"name" json:"name"`
	Value     pgtype.Float8      `db:"value" json:"value"`
	Comment   pgtype.Text        `db:"comment" json:"comment"`
	Source    string             `db:"source" json:"source"`
	UserID    pgtype.Text        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Trace struct {
	ID         string             `db:"id" json:"id"`
	ProjectID  string             `db:"project_id" json:"project_id"`
	Name       pgtype.Text        `db:"name" json:"name"`
	Input      []byte             `db:"input" json:"input"`
	Output     []byte             `db:"output" json:"output"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	UserID     pgtype.Text        `db:"user_id" json:"user_id"`
	SessionID  pgtype.Text        `db:"session_id" json:"session_id"`
	Tags       []string           `db:"tags" json:"tags"`
	StartTime  pgtype.Timestamptz `db:"start_time" json:"start_time"`
	EndTime    pgtype.Timestamptz `db:"end_time" json:"end_time"`
	TotalCost  pgtype.Float8      `db:"total_cost" json:"total_cost"`
	TokenUsage []byte             `db:"token_usage" json:"token_usage"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           string             `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Name         pgtype.Text        `db:"name" json:"name"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
