// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDatasetItemsByDatasetID = `-- name: CountDatasetItemsByDatasetID :one
SELECT COUNT(*) FROM dataset_items WHERE dataset_id = $1
`

func (q *Queries) CountDatasetItemsByDatasetID(ctx context.Context, datasetID string) (int64, error) {
	row := q.db.QueryRow(ctx, countDatasetItemsByDatasetID, datasetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTracesByProjectID = `-- name: CountTracesByProjectID :one
SELECT COUNT(*) FROM traces WHERE project_id = $1
`

func (q *Queries) CountTracesByProjectID(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTracesByProjectID, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (project_id, key, name)
VALUES ($1, $2, $3)
RETURNING id, project_id, key, name, created_at
`

type CreateAPIKeyParams struct {
	ProjectID string      `db:"project_id" json:"project_id"`
	Key       string      `db:"key" json:"key"`
	Name      pgtype.Text `db:"name" json:"name"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.ProjectID, arg.Key, arg.Name)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createDataset = `-- name: CreateDataset :one
INSERT INTO datasets (project_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, project_id, name, description, created_at
`

type CreateDatasetParams struct {
	ProjectID   string      `db:"project_id" json:"project_id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
}

func (q *Queries) CreateDataset(ctx context.Context, arg CreateDatasetParams) (Dataset, error) {
	row := q.db.QueryRow(ctx, createDataset, arg.ProjectID, arg.Name, arg.Description)
	var i Dataset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createDatasetItem = `-- name: CreateDatasetItem :one
INSERT INTO dataset_items (dataset_id, input, expected_output, metadata, source_trace_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, dataset_id, input, expected_output, metadata, source_trace_id, created_at
`

type CreateDatasetItemParams struct {
	DatasetID      string      `db:"dataset_id" json:"dataset_id"`
	Input          []byte      `db:"input" json:"input"`
	ExpectedOutput []byte      `db:"expected_output" json:"expected_output"`
	Metadata       []byte      `db:"metadata" json:"metadata"`
	SourceTraceID  pgtype.Text `db:"source_trace_id" json:"source_trace_id"`
}

func (q *Queries) CreateDatasetItem(ctx context.Context, arg CreateDatasetItemParams) (DatasetItem, error) {
	row := q.db.QueryRow(ctx, createDatasetItem,
		arg.DatasetID,
		arg.Input,
		arg.ExpectedOutput,
		arg.Metadata,
		arg.SourceTraceID,
	)
	var i DatasetItem
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.Input,
		&i.ExpectedOutput,
		&i.Metadata,
		&i.SourceTraceID,
		&i.CreatedAt,
	)
	return i, err
}

const createDatasetRun = `-- name: CreateDatasetRun :one
INSERT INTO dataset_runs (dataset_id, name)
VALUES ($1, $2)
RETURNING id, dataset_id, name, created_at
`

type CreateDatasetRunParams struct {
	DatasetID string `db:"dataset_id" json:"dataset_id"`
	Name      string `db:"name" json:"name"`
}

func (q *Queries) CreateDatasetRun(ctx context.Context, arg CreateDatasetRunParams) (DatasetRun, error) {
	row := q.db.QueryRow(ctx, createDatasetRun, arg.DatasetID, arg.Name)
	var i DatasetRun
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createDatasetRunItem = `-- name: CreateDatasetRunItem :one
INSERT INTO dataset_run_items (dataset_run_id, dataset_item_id, observation_id, score_id)
VALUES ($1, $2, $3, $4)
RETURNING id, dataset_run_id, dataset_item_id, observation_id, score_id, created_at
`

type CreateDatasetRunItemParams struct {
	DatasetRunID  string      `db:"dataset_run_id" json:"dataset_run_id"`
	DatasetItemID string      `db:"dataset_item_id" json:"dataset_item_id"`
	ObservationID pgtype.Text `db:"observation_id" json:"observation_id"`
	ScoreID       pgtype.Text `db:"score_id" json:"score_id"`
}

func (q *Queries) CreateDatasetRunItem(ctx context.Context, arg CreateDatasetRunItemParams) (DatasetRunItem, error) {
	row := q.db.QueryRow(ctx, createDatasetRunItem,
		arg.DatasetRunID,
		arg.DatasetItemID,
		arg.ObservationID,
		arg.ScoreID,
	)
	var i DatasetRunItem
	err := row.Scan(
		&i.ID,
		&i.DatasetRunID,
		&i.DatasetItemID,
		&i.ObservationID,
		&i.ScoreID,
		&i.CreatedAt,
	)
	return i, err
}

const createEvaluationRun = `-- name: CreateEvaluationRun :one
INSERT INTO evaluation_runs (project_id, evaluator_config_id, name, status, result_summary)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, evaluator_config_id, name, status, result_summary, created_at
`

type CreateEvaluationRunParams struct {
	ProjectID         string `db:"project_id" json:"project_id"`
	EvaluatorConfigID string `db:"evaluator_config_id" json:"evaluator_config_id"`
	Name              string `db:"name" json:"name"`
	Status            string `db:"status" json:"status"`
	ResultSummary     []byte `db:"result_summary" json:"result_summary"`
}

func (q *Queries) CreateEvaluationRun(ctx context.Context, arg CreateEvaluationRunParams) (EvaluationRun, error) {
	row := q.db.QueryRow(ctx, createEvaluationRun,
		arg.ProjectID,
		arg.EvaluatorConfigID,
		arg.Name,
		arg.Status,
		arg.ResultSummary,
	)
	var i EvaluationRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EvaluatorConfigID,
		&i.Name,
		&i.Status,
		&i.ResultSummary,
		&i.CreatedAt,
	)
	return i, err
}

const createEvaluatorConfig = `-- name: CreateEvaluatorConfig :one
INSERT INTO evaluator_configs (project_id, name, description, type, config, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, description, type, config, is_active, created_at
`

type CreateEvaluatorConfigParams struct {
	ProjectID   string      `db:"project_id" json:"project_id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	Type        string      `db:"type" json:"type"`
	Config      []byte      `db:"config" json:"config"`
	IsActive    bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateEvaluatorConfig(ctx context.Context, arg CreateEvaluatorConfigParams) (EvaluatorConfig, error) {
	row := q.db.QueryRow(ctx, createEvaluatorConfig,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Config,
		arg.IsActive,
	)
	var i EvaluatorConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (user_id, org_id, role)
VALUES ($1, $2, $3)
RETURNING id, user_id, org_id, role
`

type CreateMemberParams struct {
	UserID string `db:"user_id" json:"user_id"`
	OrgID  string `db:"org_id" json:"org_id"`
	Role   string `db:"role" json:"role"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember, arg.UserID, arg.OrgID, arg.Role)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Role,
	)
	return i, err
}

const createObservation = `-- name: CreateObservation :one
INSERT INTO observations (trace_id, type, name, input, output, metadata, model, model_parameters, start_time, end_time, token_usage, cost, status, parent_observation_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, trace_id, type, name, input, output, metadata, model, model_parameters, start_time, end_time, token_usage, cost, status, parent_observation_id
`

type CreateObservationParams struct {
	TraceID             string             `db:"trace_id" json:"trace_id"`
	Type                string             `db:"type" json:"type"`
	Name                pgtype.Text        `db:"name" json:"name"`
	Input               []byte             `db:"input" json:"input"`
	Output              []byte             `db:"output" json:"output"`
	Metadata            []byte             `db:"metadata" json:"metadata"`
	Model               pgtype.Text        `db:"model" json:"model"`
	ModelParameters     []byte             `db:"model_parameters" json:"model_parameters"`
	StartTime           pgtype.Timestamptz `db:"start_time" json:"start_time"`
	EndTime             pgtype.Timestamptz `db:"end_time" json:"end_time"`
	TokenUsage          []byte             `db:"token_usage" json:"token_usage"`
	Cost                pgtype.Float8      `db:"cost" json:"cost"`
	Status              string             `db:"status" json:"status"`
	ParentObservationID pgtype.Text        `db:"parent_observation_id" json:"parent_observation_id"`
}

func (q *Queries) CreateObservation(ctx context.Context, arg CreateObservationParams) (Observation, error) {
	row := q.db.QueryRow(ctx, createObservation,
		arg.TraceID,
		arg.Type,
		arg.Name,
		arg.Input,
		arg.Output,
		arg.Metadata,
		arg.Model,
		arg.ModelParameters,
		arg.StartTime,
		arg.EndTime,
		arg.TokenUsage,
		arg.Cost,
		arg.Status,
		arg.ParentObservationID,
	)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.Type,
		&i.Name,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.Model,
		&i.ModelParameters,
		&i.StartTime,
		&i.EndTime,
		&i.TokenUsage,
		&i.Cost,
		&i.Status,
		&i.ParentObservationID,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateOrganization(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, name)
	var i Organization
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, org_id)
VALUES ($1, $2)
RETURNING id, name, org_id, created_at
`

type CreateProjectParams struct {
	Name  string `db:"name" json:"name"`
	OrgID string `db:"org_id" json:"org_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.OrgID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrgID,
		&i.CreatedAt,
	)
	return i, err
}

const createPrompt = `-- name: CreatePrompt :one
INSERT INTO prompts (project_id, name, version, prompt, config, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, version, prompt, config, is_active, created_at
`

type CreatePromptParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Name      string `db:"name" json:"name"`
	Version   int32  `db:"version" json:"version"`
	Prompt    []byte `db:"prompt" json:"prompt"`
	Config    []byte `db:"config" json:"config"`
	IsActive  bool   `db:"is_active" json:"is_active"`
}

func (q *Queries) CreatePrompt(ctx context.Context, arg CreatePromptParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, createPrompt,
		arg.ProjectID,
		arg.Name,
		arg.Version,
		arg.Prompt,
		arg.Config,
		arg.IsActive,
	)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.Prompt,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createScore = `-- name: CreateScore :one
INSERT INTO scores (trace_id, name, value, comment, source, user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, trace_id, name, value, comment, source, user_id, created_at
`

type CreateScoreParams struct {
	TraceID string        `db:"trace_id" json:"trace_id"`
	Name    string        `db:"name" json:"name"`
	Value   pgtype.Float8 `db:"value" json:"value"`
	Comment pgtype.Text   `db:"comment" json:"comment"`
	Source  string        `db:"source" json:"source"`
	UserID  pgtype.Text   `db:"user_id" json:"user_id"`
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) (Score, error) {
	row := q.db.QueryRow(ctx, createScore,
		arg.TraceID,
		arg.Name,
		arg.Value,
		arg.Comment,
		arg.Source,
		arg.UserID,
	)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.Name,
		&i.Value,
		&i.Comment,
		&i.Source,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createTrace = `-- name: CreateTrace :one
INSERT INTO traces (project_id, name, input, output, metadata, user_id, session_id, tags, start_time, end_time, total_cost, token_usage)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, project_id, name, input, output, metadata, user_id, session_id, tags, start_time, end_time, total_cost, token_usage, created_at
`

type CreateTraceParams struct {
	ProjectID  string             `db:"project_id" json:"project_id"`
	Name       pgtype.Text        `db:"name" json:"name"`
	Input      []byte             `db:"input" json:"input"`
	Output     []byte             `db:"output" json:"output"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	UserID     pgtype.Text        `db:"user_id" json:"user_id"`
	SessionID  pgtype.Text        `db:"session_id" json:"session_id"`
	Tags       []string           `db:"tags" json:"tags"`
	StartTime  pgtype.Timestamptz `db:"start_time" json:"start_time"`
	EndTime    pgtype.Timestamptz `db:"end_time" json:"end_time"`
	TotalCost  pgtype.Float8      `db:"total_cost" json:"total_cost"`
	TokenUsage []byte             `db:"token_usage" json:"token_usage"`
}

func (q *Queries) CreateTrace(ctx context.Context, arg CreateTraceParams) (Trace, error) {
	row := q.db.QueryRow(ctx, createTrace,
		arg.ProjectID,
		arg.Name,
		arg.Input,
		arg.Output,
		arg.Metadata,
		arg.UserID,
		arg.SessionID,
		arg.Tags,
		arg.StartTime,
		arg.EndTime,
		arg.TotalCost,
		arg.TokenUsage,
	)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.UserID,
		&i.SessionID,
		&i.Tags,
		&i.StartTime,
		&i.EndTime,
		&i.TotalCost,
		&i.TokenUsage,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, name, created_at
`

type CreateUserParams struct {
	Email        string      `db:"email" json:"email"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	Name         pgtype.Text `db:"name" json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1 AND project_id = $2
`

type DeleteAPIKeyParams struct {
	ID        string `db:"id" json:"id"`
	ProjectID string `db:"project_id" json:"project_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.ProjectID)
	return err
}

const deleteDataset = `-- name: DeleteDataset :exec
DELETE FROM datasets WHERE id = $1
`

func (q *Queries) DeleteDataset(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDataset, id)
	return err
}

const deleteEvaluatorConfig = `-- name: DeleteEvaluatorConfig :exec
DELETE FROM evaluator_configs WHERE id = $1
`

func (q *Queries) DeleteEvaluatorConfig(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEvaluatorConfig, id)
	return err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE user_id = $1 AND org_id = $2
`

type DeleteMemberParams struct {
	UserID string `db:"user_id" json:"user_id"`
	OrgID  string `db:"org_id" json:"org_id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.UserID, arg.OrgID)
	return err
}

const getAPIKeyByKey = `-- name: GetAPIKeyByKey :one
SELECT id, project_id, key, name, created_at FROM api_keys WHERE key = $1
`

func (q *Queries) GetAPIKeyByKey(ctx context.Context, key string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByKey, key)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeysByProjectID = `-- name: GetAPIKeysByProjectID :many
SELECT id, project_id, key, name, created_at FROM api_keys WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAPIKeysByProjectID(ctx context.Context, projectID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, getAPIKeysByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivePromptByName = `-- name: GetActivePromptByName :one
SELECT id, project_id, name, version, prompt, config, is_active, created_at FROM prompts WHERE project_id = $1 AND name = $2 AND is_active = true ORDER BY version DESC LIMIT 1
`

type GetActivePromptByNameParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Name      string `db:"name" json:"name"`
}

func (q *Queries) GetActivePromptByName(ctx context.Context, arg GetActivePromptByNameParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, getActivePromptByName, arg.ProjectID, arg.Name)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.Prompt,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getDatasetByID = `-- name: GetDatasetByID :one
SELECT id, project_id, name, description, created_at FROM datasets WHERE id = $1
`

func (q *Queries) GetDatasetByID(ctx context.Context, id string) (Dataset, error) {
	row := q.db.QueryRow(ctx, getDatasetByID, id)
	var i Dataset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getDatasetItemByID = `-- name: GetDatasetItemByID :one
SELECT id, dataset_id, input, expected_output, metadata, source_trace_id, created_at FROM dataset_items WHERE id = $1
`

func (q *Queries) GetDatasetItemByID(ctx context.Context, id string) (DatasetItem, error) {
	row := q.db.QueryRow(ctx, getDatasetItemByID, id)
	var i DatasetItem
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.Input,
		&i.ExpectedOutput,
		&i.Metadata,
		&i.SourceTraceID,
		&i.CreatedAt,
	)
	return i, err
}

const getDatasetItemsByDatasetID = `-- name: GetDatasetItemsByDatasetID :many
SELECT id, dataset_id, input, expected_output, metadata, source_trace_id, created_at FROM dataset_items WHERE dataset_id = $1 ORDER BY created_at
`

func (q *Queries) GetDatasetItemsByDatasetID(ctx context.Context, datasetID string) ([]DatasetItem, error) {
	rows, err := q.db.Query(ctx, getDatasetItemsByDatasetID, datasetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatasetItem{}
	for rows.Next() {
		var i DatasetItem
		if err := rows.Scan(
			&i.ID,
			&i.DatasetID,
			&i.Input,
			&i.ExpectedOutput,
			&i.Metadata,
			&i.SourceTraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatasetRunByID = `-- name: GetDatasetRunByID :one
SELECT id, dataset_id, name, created_at FROM dataset_runs WHERE id = $1
`

func (q *Queries) GetDatasetRunByID(ctx context.Context, id string) (DatasetRun, error) {
	row := q.db.QueryRow(ctx, getDatasetRunByID, id)
	var i DatasetRun
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getDatasetRunItemByID = `-- name: GetDatasetRunItemByID :one
SELECT id, dataset_run_id, dataset_item_id, observation_id, score_id, created_at FROM dataset_run_items WHERE id = $1
`

func (q *Queries) GetDatasetRunItemByID(ctx context.Context, id string) (DatasetRunItem, error) {
	row := q.db.QueryRow(ctx, getDatasetRunItemByID, id)
	var i DatasetRunItem
	err := row.Scan(
		&i.ID,
		&i.DatasetRunID,
		&i.DatasetItemID,
		&i.ObservationID,
		&i.ScoreID,
		&i.CreatedAt,
	)
	return i, err
}

const getDatasetRunItemsByRunID = `-- name: GetDatasetRunItemsByRunID :many
SELECT id, dataset_run_id, dataset_item_id, observation_id, score_id, created_at FROM dataset_run_items WHERE dataset_run_id = $1 ORDER BY created_at
`

func (q *Queries) GetDatasetRunItemsByRunID(ctx context.Context, datasetRunID string) ([]DatasetRunItem, error) {
	rows, err := q.db.Query(ctx, getDatasetRunItemsByRunID, datasetRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatasetRunItem{}
	for rows.Next() {
		var i DatasetRunItem
		if err := rows.Scan(
			&i.ID,
			&i.DatasetRunID,
			&i.DatasetItemID,
			&i.ObservationID,
			&i.ScoreID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatasetRunsByDatasetID = `-- name: GetDatasetRunsByDatasetID :many
SELECT id, dataset_id, name, created_at FROM dataset_runs WHERE dataset_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetDatasetRunsByDatasetID(ctx context.Context, datasetID string) ([]DatasetRun, error) {
	rows, err := q.db.Query(ctx, getDatasetRunsByDatasetID, datasetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatasetRun{}
	for rows.Next() {
		var i DatasetRun
		if err := rows.Scan(
			&i.ID,
			&i.DatasetID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatasetsByProjectID = `-- name: GetDatasetsByProjectID :many
SELECT id, project_id, name, description, created_at FROM datasets WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetDatasetsByProjectID(ctx context.Context, projectID string) ([]Dataset, error) {
	rows, err := q.db.Query(ctx, getDatasetsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dataset{}
	for rows.Next() {
		var i Dataset
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvaluationRunByID = `-- name: GetEvaluationRunByID :one
SELECT id, project_id, evaluator_config_id, name, status, result_summary, created_at FROM evaluation_runs WHERE id = $1
`

func (q *Queries) GetEvaluationRunByID(ctx context.Context, id string) (EvaluationRun, error) {
	row := q.db.QueryRow(ctx, getEvaluationRunByID, id)
	var i EvaluationRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EvaluatorConfigID,
		&i.Name,
		&i.Status,
		&i.ResultSummary,
		&i.CreatedAt,
	)
	return i, err
}

const getEvaluationRunsByProjectID = `-- name: GetEvaluationRunsByProjectID :many
SELECT id, project_id, evaluator_config_id, name, status, result_summary, created_at FROM evaluation_runs WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetEvaluationRunsByProjectID(ctx context.Context, projectID string) ([]EvaluationRun, error) {
	rows, err := q.db.Query(ctx, getEvaluationRunsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvaluationRun{}
	for rows.Next() {
		var i EvaluationRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EvaluatorConfigID,
			&i.Name,
			&i.Status,
			&i.ResultSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvaluatorConfigByID = `-- name: GetEvaluatorConfigByID :one
SELECT id, project_id, name, description, type, config, is_active, created_at FROM evaluator_configs WHERE id = $1
`

func (q *Queries) GetEvaluatorConfigByID(ctx context.Context, id string) (EvaluatorConfig, error) {
	row := q.db.QueryRow(ctx, getEvaluatorConfigByID, id)
	var i EvaluatorConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getEvaluatorConfigsByProjectID = `-- name: GetEvaluatorConfigsByProjectID :many
SELECT id, project_id, name, description, type, config, is_active, created_at FROM evaluator_configs WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetEvaluatorConfigsByProjectID(ctx context.Context, projectID string) ([]EvaluatorConfig, error) {
	rows, err := q.db.Query(ctx, getEvaluatorConfigsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvaluatorConfig{}
	for rows.Next() {
		var i EvaluatorConfig
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Config,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberByUserAndOrg = `-- name: GetMemberByUserAndOrg :one
SELECT id, user_id, org_id, role FROM members WHERE user_id = $1 AND org_id = $2
`

type GetMemberByUserAndOrgParams struct {
	UserID string `db:"user_id" json:"user_id"`
	OrgID  string `db:"org_id" json:"org_id"`
}

func (q *Queries) GetMemberByUserAndOrg(ctx context.Context, arg GetMemberByUserAndOrgParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByUserAndOrg, arg.UserID, arg.OrgID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Role,
	)
	return i, err
}

const getMembersByOrgID = `-- name: GetMembersByOrgID :many
SELECT m.id, m.user_id, m.org_id, m.role, u.email, u.name as user_name FROM members m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1
ORDER BY m.id
`

type GetMembersByOrgIDRow struct {
	ID       string      `db:"id" json:"id"`
	UserID   string      `db:"user_id" json:"user_id"`
	OrgID    string      `db:"org_id" json:"org_id"`
	Role     string      `db:"role" json:"role"`
	Email    string      `db:"email" json:"email"`
	UserName pgtype.Text `db:"user_name" json:"user_name"`
}

func (q *Queries) GetMembersByOrgID(ctx context.Context, orgID string) ([]GetMembersByOrgIDRow, error) {
	rows, err := q.db.Query(ctx, getMembersByOrgID, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMembersByOrgIDRow{}
	for rows.Next() {
		var i GetMembersByOrgIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Role,
			&i.Email,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObservationByID = `-- name: GetObservationByID :one
SELECT id, trace_id, type, name, input, output, metadata, model, model_parameters, start_time, end_time, token_usage, cost, status, parent_observation_id FROM observations WHERE id = $1
`

func (q *Queries) GetObservationByID(ctx context.Context, id string) (Observation, error) {
	row := q.db.QueryRow(ctx, getObservationByID, id)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.Type,
		&i.Name,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.Model,
		&i.ModelParameters,
		&i.StartTime,
		&i.EndTime,
		&i.TokenUsage,
		&i.Cost,
		&i.Status,
		&i.ParentObservationID,
	)
	return i, err
}

const getObservationsByTraceID = `-- name: GetObservationsByTraceID :many
SELECT id, trace_id, type, name, input, output, metadata, model, model_parameters, start_time, end_time, token_usage, cost, status, parent_observation_id FROM observations 
WHERE trace_id = $1 
ORDER BY start_time ASC
`

func (q *Queries) GetObservationsByTraceID(ctx context.Context, traceID string) ([]Observation, error) {
	rows, err := q.db.Query(ctx, getObservationsByTraceID, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Observation{}
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.Type,
			&i.Name,
			&i.Input,
			&i.Output,
			&i.Metadata,
			&i.Model,
			&i.ModelParameters,
			&i.StartTime,
			&i.EndTime,
			&i.TokenUsage,
			&i.Cost,
			&i.Status,
			&i.ParentObservationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, created_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getOrganizationsByUserID = `-- name: GetOrganizationsByUserID :many
SELECT o.id, o.name, o.created_at FROM organizations o
JOIN members m ON m.org_id = o.id
WHERE m.user_id = $1
ORDER BY o.created_at DESC
`

func (q *Queries) GetOrganizationsByUserID(ctx context.Context, userID string) ([]Organization, error) {
	rows, err := q.db.Query(ctx, getOrganizationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, org_id, created_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrgID,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectsByOrgID = `-- name: GetProjectsByOrgID :many
SELECT id, name, org_id, created_at FROM projects WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetProjectsByOrgID(ctx context.Context, orgID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByOrgID, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrgID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPromptByID = `-- name: GetPromptByID :one
SELECT id, project_id, name, version, prompt, config, is_active, created_at FROM prompts WHERE id = $1
`

func (q *Queries) GetPromptByID(ctx context.Context, id string) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPromptByID, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.Prompt,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptByNameAndVersion = `-- name: GetPromptByNameAndVersion :one
SELECT id, project_id, name, version, prompt, config, is_active, created_at FROM prompts WHERE project_id = $1 AND name = $2 AND version = $3
`

type GetPromptByNameAndVersionParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Name      string `db:"name" json:"name"`
	Version   int32  `db:"version" json:"version"`
}

func (q *Queries) GetPromptByNameAndVersion(ctx context.Context, arg GetPromptByNameAndVersionParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPromptByNameAndVersion, arg.ProjectID, arg.Name, arg.Version)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.Prompt,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptsByProjectID = `-- name: GetPromptsByProjectID :many
SELECT id, project_id, name, version, prompt, config, is_active, created_at FROM prompts 
WHERE project_id = $1 
ORDER BY name, version DESC
`

func (q *Queries) GetPromptsByProjectID(ctx context.Context, projectID string) ([]Prompt, error) {
	rows, err := q.db.Query(ctx, getPromptsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prompt{}
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Version,
			&i.Prompt,
			&i.Config,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScoreAggregationByProjectID = `-- name: GetScoreAggregationByProjectID :many
SELECT s.name, COUNT(*) as count, AVG(s.value) as avg_value, MIN(s.value) as min_value, MAX(s.value) as max_value
FROM scores s
JOIN traces t ON t.id = s.trace_id
WHERE t.project_id = $1
GROUP BY s.name
ORDER BY s.name
`

type GetScoreAggregationByProjectIDRow struct {
	Name     string      `db:"name" json:"name"`
	Count    int64       `db:"count" json:"count"`
	AvgValue float64     `db:"avg_value" json:"avg_value"`
	MinValue interface{} `db:"min_value" json:"min_value"`
	MaxValue interface{} `db:"max_value" json:"max_value"`
}

func (q *Queries) GetScoreAggregationByProjectID(ctx context.Context, projectID string) ([]GetScoreAggregationByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, getScoreAggregationByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetScoreAggregationByProjectIDRow{}
	for rows.Next() {
		var i GetScoreAggregationByProjectIDRow
		if err := rows.Scan(
			&i.Name,
			&i.Count,
			&i.AvgValue,
			&i.MinValue,
			&i.MaxValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScoreByID = `-- name: GetScoreByID :one
SELECT id, trace_id, name, value, comment, source, user_id, created_at FROM scores WHERE id = $1
`

func (q *Queries) GetScoreByID(ctx context.Context, id string) (Score, error) {
	row := q.db.QueryRow(ctx, getScoreByID, id)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.Name,
		&i.Value,
		&i.Comment,
		&i.Source,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getScoresByTraceID = `-- name: GetScoresByTraceID :many
SELECT id, trace_id, name, value, comment, source, user_id, created_at FROM scores WHERE trace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetScoresByTraceID(ctx context.Context, traceID string) ([]Score, error) {
	rows, err := q.db.Query(ctx, getScoresByTraceID, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Score{}
	for rows.Next() {
		var i Score
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.Name,
			&i.Value,
			&i.Comment,
			&i.Source,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScoresByTraceIDAndName = `-- name: GetScoresByTraceIDAndName :many
SELECT id, trace_id, name, value, comment, source, user_id, created_at FROM scores WHERE trace_id = $1 AND name = $2 ORDER BY created_at DESC
`

type GetScoresByTraceIDAndNameParams struct {
	TraceID string `db:"trace_id" json:"trace_id"`
	Name    string `db:"name" json:"name"`
}

func (q *Queries) GetScoresByTraceIDAndName(ctx context.Context, arg GetScoresByTraceIDAndNameParams) ([]Score, error) {
	rows, err := q.db.Query(ctx, getScoresByTraceIDAndName, arg.TraceID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Score{}
	for rows.Next() {
		var i Score
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.Name,
			&i.Value,
			&i.Comment,
			&i.Source,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTraceByID = `-- name: GetTraceByID :one
SELECT id, project_id, name, input, output, metadata, user_id, session_id, tags, start_time, end_time, total_cost, token_usage, created_at FROM traces WHERE id = $1
`

func (q *Queries) GetTraceByID(ctx context.Context, id string) (Trace, error) {
	row := q.db.QueryRow(ctx, getTraceByID, id)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.UserID,
		&i.SessionID,
		&i.Tags,
		&i.StartTime,
		&i.EndTime,
		&i.TotalCost,
		&i.TokenUsage,
		&i.CreatedAt,
	)
	return i, err
}

const getTraceCostOverTimeByProjectID = `-- name: GetTraceCostOverTimeByProjectID :many
SELECT
  date_trunc('day', start_time)::timestamptz as time_bucket,
  COUNT(*) as trace_count,
  COALESCE(SUM(total_cost), 0) as total_cost,
  COALESCE(AVG(total_cost), 0) as avg_cost
FROM traces
WHERE project_id = $1 AND start_time >= $2 AND start_time < $3 AND total_cost IS NOT NULL
GROUP BY date_trunc('day', start_time)
ORDER BY time_bucket
`

type GetTraceCostOverTimeByProjectIDParams struct {
	ProjectID   string             `db:"project_id" json:"project_id"`
	StartTime   pgtype.Timestamptz `db:"start_time" json:"start_time"`
	StartTime_2 pgtype.Timestamptz `db:"start_time_2" json:"start_time_2"`
}

type GetTraceCostOverTimeByProjectIDRow struct {
	TimeBucket pgtype.Timestamptz `db:"time_bucket" json:"time_bucket"`
	TraceCount int64              `db:"trace_count" json:"trace_count"`
	TotalCost  interface{}        `db:"total_cost" json:"total_cost"`
	AvgCost    interface{}        `db:"avg_cost" json:"avg_cost"`
}

func (q *Queries) GetTraceCostOverTimeByProjectID(ctx context.Context, arg GetTraceCostOverTimeByProjectIDParams) ([]GetTraceCostOverTimeByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, getTraceCostOverTimeByProjectID, arg.ProjectID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTraceCostOverTimeByProjectIDRow{}
	for rows.Next() {
		var i GetTraceCostOverTimeByProjectIDRow
		if err := rows.Scan(
			&i.TimeBucket,
			&i.TraceCount,
			&i.TotalCost,
			&i.AvgCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTraceCostStatsByProjectID = `-- name: GetTraceCostStatsByProjectID :one
SELECT
  COUNT(*) as total_traces,
  SUM(total_cost) as total_cost,
  AVG(total_cost) as avg_cost,
  MIN(total_cost) as min_cost,
  MAX(total_cost) as max_cost
FROM traces
WHERE project_id = $1 AND total_cost IS NOT NULL
`

type GetTraceCostStatsByProjectIDRow struct {
	TotalTraces int64       `db:"total_traces" json:"total_traces"`
	TotalCost   int64       `db:"total_cost" json:"total_cost"`
	AvgCost     float64     `db:"avg_cost" json:"avg_cost"`
	MinCost     interface{} `db:"min_cost" json:"min_cost"`
	MaxCost     interface{} `db:"max_cost" json:"max_cost"`
}

func (q *Queries) GetTraceCostStatsByProjectID(ctx context.Context, projectID string) (GetTraceCostStatsByProjectIDRow, error) {
	row := q.db.QueryRow(ctx, getTraceCostStatsByProjectID, projectID)
	var i GetTraceCostStatsByProjectIDRow
	err := row.Scan(
		&i.TotalTraces,
		&i.TotalCost,
		&i.AvgCost,
		&i.MinCost,
		&i.MaxCost,
	)
	return i, err
}

const getTraceCountByProjectIDAndTimeRange = `-- name: GetTraceCountByProjectIDAndTimeRange :one
SELECT COUNT(*) as count
FROM traces
WHERE project_id = $1 AND start_time >= $2 AND start_time < $3
`

type GetTraceCountByProjectIDAndTimeRangeParams struct {
	ProjectID   string             `db:"project_id" json:"project_id"`
	StartTime   pgtype.Timestamptz `db:"start_time" json:"start_time"`
	StartTime_2 pgtype.Timestamptz `db:"start_time_2" json:"start_time_2"`
}

func (q *Queries) GetTraceCountByProjectIDAndTimeRange(ctx context.Context, arg GetTraceCountByProjectIDAndTimeRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTraceCountByProjectIDAndTimeRange, arg.ProjectID, arg.StartTime, arg.StartTime_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTraceCountOverTimeByProjectID = `-- name: GetTraceCountOverTimeByProjectID :many
SELECT
  date_trunc('day', t.start_time)::timestamptz as time_bucket,
  COUNT(*) as trace_count,
  COUNT(*) FILTER (WHERE EXISTS (
    SELECT 1 FROM observations o WHERE o.trace_id = t.id AND o.status = 'ERROR'
  )) as error_count
FROM traces t
WHERE t.project_id = $1 AND t.start_time >= $2 AND t.start_time < $3
GROUP BY date_trunc('day', t.start_time)
ORDER BY time_bucket
`

type GetTraceCountOverTimeByProjectIDParams struct {
	ProjectID   string             `db:"project_id" json:"project_id"`
	StartTime   pgtype.Timestamptz `db:"start_time" json:"start_time"`
	StartTime_2 pgtype.Timestamptz `db:"start_time_2" json:"start_time_2"`
}

type GetTraceCountOverTimeByProjectIDRow struct {
	TimeBucket pgtype.Timestamptz `db:"time_bucket" json:"time_bucket"`
	TraceCount int64              `db:"trace_count" json:"trace_count"`
	ErrorCount int64              `db:"error_count" json:"error_count"`
}

func (q *Queries) GetTraceCountOverTimeByProjectID(ctx context.Context, arg GetTraceCountOverTimeByProjectIDParams) ([]GetTraceCountOverTimeByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, getTraceCountOverTimeByProjectID, arg.ProjectID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTraceCountOverTimeByProjectIDRow{}
	for rows.Next() {
		var i GetTraceCountOverTimeByProjectIDRow
		if err := rows.Scan(&i.TimeBucket, &i.TraceCount, &i.ErrorCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTraceErrorRateByProjectID = `-- name: GetTraceErrorRateByProjectID :one
SELECT
  COUNT(*) as total_traces,
  COUNT(*) FILTER (WHERE EXISTS (
    SELECT 1 FROM observations o WHERE o.trace_id = traces.id AND o.status = 'ERROR'
  )) as error_traces
FROM traces
WHERE project_id = $1
`

type GetTraceErrorRateByProjectIDRow struct {
	TotalTraces int64 `db:"total_traces" json:"total_traces"`
	ErrorTraces int64 `db:"error_traces" json:"error_traces"`
}

func (q *Queries) GetTraceErrorRateByProjectID(ctx context.Context, projectID string) (GetTraceErrorRateByProjectIDRow, error) {
	row := q.db.QueryRow(ctx, getTraceErrorRateByProjectID, projectID)
	var i GetTraceErrorRateByProjectIDRow
	err := row.Scan(&i.TotalTraces, &i.ErrorTraces)
	return i, err
}

const getTraceLatencyOverTimeByProjectID = `-- name: GetTraceLatencyOverTimeByProjectID :many
SELECT
  date_trunc('day', start_time)::timestamptz as time_bucket,
  COUNT(*) as trace_count,
  COALESCE(AVG(EXTRACT(EPOCH FROM (end_time - start_time))), 0) as avg_latency_seconds,
  COALESCE(MIN(EXTRACT(EPOCH FROM (end_time - start_time))), 0) as min_latency_seconds,
  COALESCE(MAX(EXTRACT(EPOCH FROM (end_time - start_time))), 0) as max_latency_seconds
FROM traces
WHERE project_id = $1 AND start_time >= $2 AND start_time < $3 AND end_time IS NOT NULL AND start_time IS NOT NULL
GROUP BY date_trunc('day', start_time)
ORDER BY time_bucket
`

type GetTraceLatencyOverTimeByProjectIDParams struct {
	ProjectID   string             `db:"project_id" json:"project_id"`
	StartTime   pgtype.Timestamptz `db:"start_time" json:"start_time"`
	StartTime_2 pgtype.Timestamptz `db:"start_time_2" json:"start_time_2"`
}

type GetTraceLatencyOverTimeByProjectIDRow struct {
	TimeBucket        pgtype.Timestamptz `db:"time_bucket" json:"time_bucket"`
	TraceCount        int64              `db:"trace_count" json:"trace_count"`
	AvgLatencySeconds interface{}        `db:"avg_latency_seconds" json:"avg_latency_seconds"`
	MinLatencySeconds interface{}        `db:"min_latency_seconds" json:"min_latency_seconds"`
	MaxLatencySeconds interface{}        `db:"max_latency_seconds" json:"max_latency_seconds"`
}

func (q *Queries) GetTraceLatencyOverTimeByProjectID(ctx context.Context, arg GetTraceLatencyOverTimeByProjectIDParams) ([]GetTraceLatencyOverTimeByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, getTraceLatencyOverTimeByProjectID, arg.ProjectID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTraceLatencyOverTimeByProjectIDRow{}
	for rows.Next() {
		var i GetTraceLatencyOverTimeByProjectIDRow
		if err := rows.Scan(
			&i.TimeBucket,
			&i.TraceCount,
			&i.AvgLatencySeconds,
			&i.MinLatencySeconds,
			&i.MaxLatencySeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTraceLatencyStatsByProjectID = `-- name: GetTraceLatencyStatsByProjectID :one
SELECT
  COUNT(*) as total_traces,
  AVG(EXTRACT(EPOCH FROM (end_time - start_time))) as avg_latency_seconds,
  MIN(EXTRACT(EPOCH FROM (end_time - start_time))) as min_latency_seconds,
  MAX(EXTRACT(EPOCH FROM (end_time - start_time))) as max_latency_seconds
FROM traces
WHERE project_id = $1 AND end_time IS NOT NULL AND start_time IS NOT NULL
`

type GetTraceLatencyStatsByProjectIDRow struct {
	TotalTraces       int64       `db:"total_traces" json:"total_traces"`
	AvgLatencySeconds float64     `db:"avg_latency_seconds" json:"avg_latency_seconds"`
	MinLatencySeconds interface{} `db:"min_latency_seconds" json:"min_latency_seconds"`
	MaxLatencySeconds interface{} `db:"max_latency_seconds" json:"max_latency_seconds"`
}

func (q *Queries) GetTraceLatencyStatsByProjectID(ctx context.Context, projectID string) (GetTraceLatencyStatsByProjectIDRow, error) {
	row := q.db.QueryRow(ctx, getTraceLatencyStatsByProjectID, projectID)
	var i GetTraceLatencyStatsByProjectIDRow
	err := row.Scan(
		&i.TotalTraces,
		&i.AvgLatencySeconds,
		&i.MinLatencySeconds,
		&i.MaxLatencySeconds,
	)
	return i, err
}

const getTraceTokenUsageOverTimeByProjectID = `-- name: GetTraceTokenUsageOverTimeByProjectID :many
SELECT
  date_trunc('day', start_time)::timestamptz as time_bucket,
  COUNT(*) as trace_count,
  COALESCE(SUM((token_usage->>'total_tokens')::bigint), 0) as total_tokens,
  COALESCE(SUM((token_usage->>'input_tokens')::bigint), 0) as total_input_tokens,
  COALESCE(SUM((token_usage->>'output_tokens')::bigint), 0) as total_output_tokens
FROM traces
WHERE project_id = $1 AND start_time >= $2 AND start_time < $3 AND token_usage IS NOT NULL
GROUP BY date_trunc('day', start_time)
ORDER BY time_bucket
`

type GetTraceTokenUsageOverTimeByProjectIDParams struct {
	ProjectID   string             `db:"project_id" json:"project_id"`
	StartTime   pgtype.Timestamptz `db:"start_time" json:"start_time"`
	StartTime_2 pgtype.Timestamptz `db:"start_time_2" json:"start_time_2"`
}

type GetTraceTokenUsageOverTimeByProjectIDRow struct {
	TimeBucket        pgtype.Timestamptz `db:"time_bucket" json:"time_bucket"`
	TraceCount        int64              `db:"trace_count" json:"trace_count"`
	TotalTokens       interface{}        `db:"total_tokens" json:"total_tokens"`
	TotalInputTokens  interface{}        `db:"total_input_tokens" json:"total_input_tokens"`
	TotalOutputTokens interface{}        `db:"total_output_tokens" json:"total_output_tokens"`
}

func (q *Queries) GetTraceTokenUsageOverTimeByProjectID(ctx context.Context, arg GetTraceTokenUsageOverTimeByProjectIDParams) ([]GetTraceTokenUsageOverTimeByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, getTraceTokenUsageOverTimeByProjectID, arg.ProjectID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTraceTokenUsageOverTimeByProjectIDRow{}
	for rows.Next() {
		var i GetTraceTokenUsageOverTimeByProjectIDRow
		if err := rows.Scan(
			&i.TimeBucket,
			&i.TraceCount,
			&i.TotalTokens,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTraceTokenUsageStatsByProjectID = `-- name: GetTraceTokenUsageStatsByProjectID :one
SELECT
  COUNT(*) as total_traces,
  SUM((token_usage->>'total_tokens')::bigint) as total_tokens,
  AVG((token_usage->>'total_tokens')::bigint) as avg_tokens,
  SUM((token_usage->>'input_tokens')::bigint) as total_input_tokens,
  SUM((token_usage->>'output_tokens')::bigint) as total_output_tokens
FROM traces
WHERE project_id = $1 AND token_usage IS NOT NULL
`

type GetTraceTokenUsageStatsByProjectIDRow struct {
	TotalTraces       int64   `db:"total_traces" json:"total_traces"`
	TotalTokens       int64   `db:"total_tokens" json:"total_tokens"`
	AvgTokens         float64 `db:"avg_tokens" json:"avg_tokens"`
	TotalInputTokens  int64   `db:"total_input_tokens" json:"total_input_tokens"`
	TotalOutputTokens int64   `db:"total_output_tokens" json:"total_output_tokens"`
}

func (q *Queries) GetTraceTokenUsageStatsByProjectID(ctx context.Context, projectID string) (GetTraceTokenUsageStatsByProjectIDRow, error) {
	row := q.db.QueryRow(ctx, getTraceTokenUsageStatsByProjectID, projectID)
	var i GetTraceTokenUsageStatsByProjectIDRow
	err := row.Scan(
		&i.TotalTraces,
		&i.TotalTokens,
		&i.AvgTokens,
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
	)
	return i, err
}

const getTraceWithProject = `-- name: GetTraceWithProject :one
SELECT t.id, t.project_id, t.name, t.input, t.output, t.metadata, t.user_id, t.session_id, t.tags, t.start_time, t.end_time, t.total_cost, t.token_usage, t.created_at, p.name as project_name FROM traces t
JOIN projects p ON p.id = t.project_id
WHERE t.id = $1
`

type GetTraceWithProjectRow struct {
	ID          string             `db:"id" json:"id"`
	ProjectID   string             `db:"project_id" json:"project_id"`
	Name        pgtype.Text        `db:"name" json:"name"`
	Input       []byte             `db:"input" json:"input"`
	Output      []byte             `db:"output" json:"output"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	UserID      pgtype.Text        `db:"user_id" json:"user_id"`
	SessionID   pgtype.Text        `db:"session_id" json:"session_id"`
	Tags        []string           `db:"tags" json:"tags"`
	StartTime   pgtype.Timestamptz `db:"start_time" json:"start_time"`
	EndTime     pgtype.Timestamptz `db:"end_time" json:"end_time"`
	TotalCost   pgtype.Float8      `db:"total_cost" json:"total_cost"`
	TokenUsage  []byte             `db:"token_usage" json:"token_usage"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ProjectName string             `db:"project_name" json:"project_name"`
}

func (q *Queries) GetTraceWithProject(ctx context.Context, id string) (GetTraceWithProjectRow, error) {
	row := q.db.QueryRow(ctx, getTraceWithProject, id)
	var i GetTraceWithProjectRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.UserID,
		&i.SessionID,
		&i.Tags,
		&i.StartTime,
		&i.EndTime,
		&i.TotalCost,
		&i.TokenUsage,
		&i.CreatedAt,
		&i.ProjectName,
	)
	return i, err
}

const getTracesByProjectID = `-- name: GetTracesByProjectID :many
SELECT id, project_id, name, input, output, metadata, user_id, session_id, tags, start_time, end_time, total_cost, token_usage, created_at FROM traces 
WHERE project_id = $1 
ORDER BY start_time DESC
LIMIT $2 OFFSET $3
`

type GetTracesByProjectIDParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Limit     int32  `db:"limit" json:"limit"`
	Offset    int32  `db:"offset" json:"offset"`
}

func (q *Queries) GetTracesByProjectID(ctx context.Context, arg GetTracesByProjectIDParams) ([]Trace, error) {
	rows, err := q.db.Query(ctx, getTracesByProjectID, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trace{}
	for rows.Next() {
		var i Trace
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Input,
			&i.Output,
			&i.Metadata,
			&i.UserID,
			&i.SessionID,
			&i.Tags,
			&i.StartTime,
			&i.EndTime,
			&i.TotalCost,
			&i.TokenUsage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTracesByProjectIDAndName = `-- name: GetTracesByProjectIDAndName :many
SELECT id, project_id, name, input, output, metadata, user_id, session_id, tags, start_time, end_time, total_cost, token_usage, created_at FROM traces 
WHERE project_id = $1 AND name = $2
ORDER BY start_time DESC
LIMIT $3 OFFSET $4
`

type GetTracesByProjectIDAndNameParams struct {
	ProjectID string      `db:"project_id" json:"project_id"`
	Name      pgtype.Text `db:"name" json:"name"`
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
}

func (q *Queries) GetTracesByProjectIDAndName(ctx context.Context, arg GetTracesByProjectIDAndNameParams) ([]Trace, error) {
	rows, err := q.db.Query(ctx, getTracesByProjectIDAndName,
		arg.ProjectID,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trace{}
	for rows.Next() {
		var i Trace
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Input,
			&i.Output,
			&i.Metadata,
			&i.UserID,
			&i.SessionID,
			&i.Tags,
			&i.StartTime,
			&i.EndTime,
			&i.TotalCost,
			&i.TokenUsage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, email, password_hash, name, created_at FROM users WHERE id = $1
`

// queries.sql
// Type-safe SQL queries for sqlc
func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const updateEvaluationRunStatus = `-- name: UpdateEvaluationRunStatus :exec
UPDATE evaluation_runs SET status = $2, result_summary = $3 WHERE id = $1
`

type UpdateEvaluationRunStatusParams struct {
	ID            string `db:"id" json:"id"`
	Status        string `db:"status" json:"status"`
	ResultSummary []byte `db:"result_summary" json:"result_summary"`
}

func (q *Queries) UpdateEvaluationRunStatus(ctx context.Context, arg UpdateEvaluationRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateEvaluationRunStatus, arg.ID, arg.Status, arg.ResultSummary)
	return err
}

const updateEvaluatorConfig = `-- name: UpdateEvaluatorConfig :exec
UPDATE evaluator_configs
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    config = COALESCE($4, config),
    is_active = COALESCE($5, is_active)
WHERE id = $1
`

type UpdateEvaluatorConfigParams struct {
	ID          string      `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	Config      []byte      `db:"config" json:"config"`
	IsActive    bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateEvaluatorConfig(ctx context.Context, arg UpdateEvaluatorConfigParams) error {
	_, err := q.db.Exec(ctx, updateEvaluatorConfig,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.IsActive,
	)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE members SET role = $3 WHERE user_id = $1 AND org_id = $2
`

type UpdateMemberRoleParams struct {
	UserID string `db:"user_id" json:"user_id"`
	OrgID  string `db:"org_id" json:"org_id"`
	Role   string `db:"role" json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.UserID, arg.OrgID, arg.Role)
	return err
}

const updatePromptActive = `-- name: UpdatePromptActive :exec
UPDATE prompts SET is_active = $3 WHERE project_id = $1 AND name = $2
`

type UpdatePromptActiveParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Name      string `db:"name" json:"name"`
	IsActive  bool   `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdatePromptActive(ctx context.Context, arg UpdatePromptActiveParams) error {
	_, err := q.db.Exec(ctx, updatePromptActive, arg.ProjectID, arg.Name, arg.IsActive)
	return err
}

const updatePromptActiveByVersion = `-- name: UpdatePromptActiveByVersion :exec
UPDATE prompts SET is_active = $3 WHERE project_id = $1 AND name = $2 AND version = $4
`

type UpdatePromptActiveByVersionParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Name      string `db:"name" json:"name"`
	IsActive  bool   `db:"is_active" json:"is_active"`
	Version   int32  `db:"version" json:"version"`
}

func (q *Queries) UpdatePromptActiveByVersion(ctx context.Context, arg UpdatePromptActiveByVersionParams) error {
	_, err := q.db.Exec(ctx, updatePromptActiveByVersion,
		arg.ProjectID,
		arg.Name,
		arg.IsActive,
		arg.Version,
	)
	return err
}

const updateTrace = `-- name: UpdateTrace :one
UPDATE traces
SET name = COALESCE($2, name),
    input = COALESCE($3, input),
    output = COALESCE($4, output),
    metadata = COALESCE($5, metadata),
    end_time = COALESCE($6, end_time),
    total_cost = COALESCE($7, total_cost),
    token_usage = COALESCE($8, token_usage)
WHERE id = $1
RETURNING id, project_id, name, input, output, metadata, user_id, session_id, tags, start_time, end_time, total_cost, token_usage, created_at
`

type UpdateTraceParams struct {
	ID         string             `db:"id" json:"id"`
	Name       pgtype.Text        `db:"name" json:"name"`
	Input      []byte             `db:"input" json:"input"`
	Output     []byte             `db:"output" json:"output"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	EndTime    pgtype.Timestamptz `db:"end_time" json:"end_time"`
	TotalCost  pgtype.Float8      `db:"total_cost" json:"total_cost"`
	TokenUsage []byte             `db:"token_usage" json:"token_usage"`
}

func (q *Queries) UpdateTrace(ctx context.Context, arg UpdateTraceParams) (Trace, error) {
	row := q.db.QueryRow(ctx, updateTrace,
		arg.ID,
		arg.Name,
		arg.Input,
		arg.Output,
		arg.Metadata,
		arg.EndTime,
		arg.TotalCost,
		arg.TokenUsage,
	)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.UserID,
		&i.SessionID,
		&i.Tags,
		&i.StartTime,
		&i.EndTime,
		&i.TotalCost,
		&i.TokenUsage,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users SET name = $2 WHERE id = $1
`

type UpdateUserNameParams struct {
	ID   string      `db:"id" json:"id"`
	Name pgtype.Text `db:"name" json:"name"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.ID, arg.Name)
	return err
}
