// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (project_id, key, name)
VALUES ($1, $2, $3)
RETURNING id, project_id, key, name, created_at
`

type CreateAPIKeyParams struct {
	ProjectID string      `db:"project_id" json:"project_id"`
	Key       string      `db:"key" json:"key"`
	Name      pgtype.Text `db:"name" json:"name"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.ProjectID, arg.Key, arg.Name)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createDataset = `-- name: CreateDataset :one
INSERT INTO datasets (project_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, project_id, name, description, created_at
`

type CreateDatasetParams struct {
	ProjectID   string      `db:"project_id" json:"project_id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
}

func (q *Queries) CreateDataset(ctx context.Context, arg CreateDatasetParams) (Dataset, error) {
	row := q.db.QueryRow(ctx, createDataset, arg.ProjectID, arg.Name, arg.Description)
	var i Dataset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createDatasetItem = `-- name: CreateDatasetItem :one
INSERT INTO dataset_items (dataset_id, input, expected_output, metadata, source_trace_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, dataset_id, input, expected_output, metadata, source_trace_id, created_at
`

type CreateDatasetItemParams struct {
	DatasetID      string      `db:"dataset_id" json:"dataset_id"`
	Input          []byte      `db:"input" json:"input"`
	ExpectedOutput []byte      `db:"expected_output" json:"expected_output"`
	Metadata       []byte      `db:"metadata" json:"metadata"`
	SourceTraceID  pgtype.Text `db:"source_trace_id" json:"source_trace_id"`
}

func (q *Queries) CreateDatasetItem(ctx context.Context, arg CreateDatasetItemParams) (DatasetItem, error) {
	row := q.db.QueryRow(ctx, createDatasetItem,
		arg.DatasetID,
		arg.Input,
		arg.ExpectedOutput,
		arg.Metadata,
		arg.SourceTraceID,
	)
	var i DatasetItem
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.Input,
		&i.ExpectedOutput,
		&i.Metadata,
		&i.SourceTraceID,
		&i.CreatedAt,
	)
	return i, err
}

const createDatasetRun = `-- name: CreateDatasetRun :one
INSERT INTO dataset_runs (dataset_id, name)
VALUES ($1, $2)
RETURNING id, dataset_id, name, created_at
`

type CreateDatasetRunParams struct {
	DatasetID string `db:"dataset_id" json:"dataset_id"`
	Name      string `db:"name" json:"name"`
}

func (q *Queries) CreateDatasetRun(ctx context.Context, arg CreateDatasetRunParams) (DatasetRun, error) {
	row := q.db.QueryRow(ctx, createDatasetRun, arg.DatasetID, arg.Name)
	var i DatasetRun
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createDatasetRunItem = `-- name: CreateDatasetRunItem :one
INSERT INTO dataset_run_items (dataset_run_id, dataset_item_id, observation_id, score_id)
VALUES ($1, $2, $3, $4)
RETURNING id, dataset_run_id, dataset_item_id, observation_id, score_id, created_at
`

type CreateDatasetRunItemParams struct {
	DatasetRunID  string      `db:"dataset_run_id" json:"dataset_run_id"`
	DatasetItemID string      `db:"dataset_item_id" json:"dataset_item_id"`
	ObservationID pgtype.Text `db:"observation_id" json:"observation_id"`
	ScoreID       pgtype.Text `db:"score_id" json:"score_id"`
}

func (q *Queries) CreateDatasetRunItem(ctx context.Context, arg CreateDatasetRunItemParams) (DatasetRunItem, error) {
	row := q.db.QueryRow(ctx, createDatasetRunItem,
		arg.DatasetRunID,
		arg.DatasetItemID,
		arg.ObservationID,
		arg.ScoreID,
	)
	var i DatasetRunItem
	err := row.Scan(
		&i.ID,
		&i.DatasetRunID,
		&i.DatasetItemID,
		&i.ObservationID,
		&i.ScoreID,
		&i.CreatedAt,
	)
	return i, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (user_id, org_id, role)
VALUES ($1, $2, $3)
RETURNING id, user_id, org_id, role
`

type CreateMemberParams struct {
	UserID string `db:"user_id" json:"user_id"`
	OrgID  string `db:"org_id" json:"org_id"`
	Role   string `db:"role" json:"role"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember, arg.UserID, arg.OrgID, arg.Role)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Role,
	)
	return i, err
}

const createObservation = `-- name: CreateObservation :one
INSERT INTO observations (trace_id, type, name, input, output, metadata, model, model_parameters, start_time, end_time, token_usage, cost, status, parent_observation_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, trace_id, type, name, input, output, metadata, model, model_parameters, start_time, end_time, token_usage, cost, status, parent_observation_id
`

type CreateObservationParams struct {
	TraceID             string             `db:"trace_id" json:"trace_id"`
	Type                string             `db:"type" json:"type"`
	Name                pgtype.Text        `db:"name" json:"name"`
	Input               []byte             `db:"input" json:"input"`
	Output              []byte             `db:"output" json:"output"`
	Metadata            []byte             `db:"metadata" json:"metadata"`
	Model               pgtype.Text        `db:"model" json:"model"`
	ModelParameters     []byte             `db:"model_parameters" json:"model_parameters"`
	StartTime           pgtype.Timestamptz `db:"start_time" json:"start_time"`
	EndTime             pgtype.Timestamptz `db:"end_time" json:"end_time"`
	TokenUsage          []byte             `db:"token_usage" json:"token_usage"`
	Cost                pgtype.Float8      `db:"cost" json:"cost"`
	Status              string             `db:"status" json:"status"`
	ParentObservationID pgtype.Text        `db:"parent_observation_id" json:"parent_observation_id"`
}

func (q *Queries) CreateObservation(ctx context.Context, arg CreateObservationParams) (Observation, error) {
	row := q.db.QueryRow(ctx, createObservation,
		arg.TraceID,
		arg.Type,
		arg.Name,
		arg.Input,
		arg.Output,
		arg.Metadata,
		arg.Model,
		arg.ModelParameters,
		arg.StartTime,
		arg.EndTime,
		arg.TokenUsage,
		arg.Cost,
		arg.Status,
		arg.ParentObservationID,
	)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.Type,
		&i.Name,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.Model,
		&i.ModelParameters,
		&i.StartTime,
		&i.EndTime,
		&i.TokenUsage,
		&i.Cost,
		&i.Status,
		&i.ParentObservationID,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateOrganization(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, name)
	var i Organization
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, org_id)
VALUES ($1, $2)
RETURNING id, name, org_id, created_at
`

type CreateProjectParams struct {
	Name  string `db:"name" json:"name"`
	OrgID string `db:"org_id" json:"org_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.OrgID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrgID,
		&i.CreatedAt,
	)
	return i, err
}

const createPrompt = `-- name: CreatePrompt :one
INSERT INTO prompts (project_id, name, version, prompt, config, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, version, prompt, config, is_active, created_at
`

type CreatePromptParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Name      string `db:"name" json:"name"`
	Version   int32  `db:"version" json:"version"`
	Prompt    []byte `db:"prompt" json:"prompt"`
	Config    []byte `db:"config" json:"config"`
	IsActive  bool   `db:"is_active" json:"is_active"`
}

func (q *Queries) CreatePrompt(ctx context.Context, arg CreatePromptParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, createPrompt,
		arg.ProjectID,
		arg.Name,
		arg.Version,
		arg.Prompt,
		arg.Config,
		arg.IsActive,
	)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.Prompt,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createScore = `-- name: CreateScore :one
INSERT INTO scores (trace_id, name, value, comment, source, user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, trace_id, name, value, comment, source, user_id, created_at
`

type CreateScoreParams struct {
	TraceID string        `db:"trace_id" json:"trace_id"`
	Name    string        `db:"name" json:"name"`
	Value   pgtype.Float8 `db:"value" json:"value"`
	Comment pgtype.Text   `db:"comment" json:"comment"`
	Source  string        `db:"source" json:"source"`
	UserID  pgtype.Text   `db:"user_id" json:"user_id"`
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) (Score, error) {
	row := q.db.QueryRow(ctx, createScore,
		arg.TraceID,
		arg.Name,
		arg.Value,
		arg.Comment,
		arg.Source,
		arg.UserID,
	)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.Name,
		&i.Value,
		&i.Comment,
		&i.Source,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createTrace = `-- name: CreateTrace :one
INSERT INTO traces (project_id, name, input, output, metadata, user_id, session_id, tags, start_time, end_time, total_cost, token_usage)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, project_id, name, input, output, metadata, user_id, session_id, tags, start_time, end_time, total_cost, token_usage, created_at
`

type CreateTraceParams struct {
	ProjectID  string             `db:"project_id" json:"project_id"`
	Name       pgtype.Text        `db:"name" json:"name"`
	Input      []byte             `db:"input" json:"input"`
	Output     []byte             `db:"output" json:"output"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	UserID     pgtype.Text        `db:"user_id" json:"user_id"`
	SessionID  pgtype.Text        `db:"session_id" json:"session_id"`
	Tags       []string           `db:"tags" json:"tags"`
	StartTime  pgtype.Timestamptz `db:"start_time" json:"start_time"`
	EndTime    pgtype.Timestamptz `db:"end_time" json:"end_time"`
	TotalCost  pgtype.Float8      `db:"total_cost" json:"total_cost"`
	TokenUsage []byte             `db:"token_usage" json:"token_usage"`
}

func (q *Queries) CreateTrace(ctx context.Context, arg CreateTraceParams) (Trace, error) {
	row := q.db.QueryRow(ctx, createTrace,
		arg.ProjectID,
		arg.Name,
		arg.Input,
		arg.Output,
		arg.Metadata,
		arg.UserID,
		arg.SessionID,
		arg.Tags,
		arg.StartTime,
		arg.EndTime,
		arg.TotalCost,
		arg.TokenUsage,
	)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.UserID,
		&i.SessionID,
		&i.Tags,
		&i.StartTime,
		&i.EndTime,
		&i.TotalCost,
		&i.TokenUsage,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, name, created_at
`

type CreateUserParams struct {
	Email        string      `db:"email" json:"email"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	Name         pgtype.Text `db:"name" json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1 AND project_id = $2
`

type DeleteAPIKeyParams struct {
	ID        string `db:"id" json:"id"`
	ProjectID string `db:"project_id" json:"project_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.ProjectID)
	return err
}

const getAPIKeyByKey = `-- name: GetAPIKeyByKey :one
SELECT id, project_id, key, name, created_at FROM api_keys WHERE key = $1
`

func (q *Queries) GetAPIKeyByKey(ctx context.Context, key string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByKey, key)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeysByProjectID = `-- name: GetAPIKeysByProjectID :many
SELECT id, project_id, key, name, created_at FROM api_keys WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAPIKeysByProjectID(ctx context.Context, projectID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, getAPIKeysByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivePromptByName = `-- name: GetActivePromptByName :one
SELECT id, project_id, name, version, prompt, config, is_active, created_at FROM prompts WHERE project_id = $1 AND name = $2 AND is_active = true ORDER BY version DESC LIMIT 1
`

type GetActivePromptByNameParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Name      string `db:"name" json:"name"`
}

func (q *Queries) GetActivePromptByName(ctx context.Context, arg GetActivePromptByNameParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, getActivePromptByName, arg.ProjectID, arg.Name)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.Prompt,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getDatasetByID = `-- name: GetDatasetByID :one
SELECT id, project_id, name, description, created_at FROM datasets WHERE id = $1
`

func (q *Queries) GetDatasetByID(ctx context.Context, id string) (Dataset, error) {
	row := q.db.QueryRow(ctx, getDatasetByID, id)
	var i Dataset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getDatasetItemByID = `-- name: GetDatasetItemByID :one
SELECT id, dataset_id, input, expected_output, metadata, source_trace_id, created_at FROM dataset_items WHERE id = $1
`

func (q *Queries) GetDatasetItemByID(ctx context.Context, id string) (DatasetItem, error) {
	row := q.db.QueryRow(ctx, getDatasetItemByID, id)
	var i DatasetItem
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.Input,
		&i.ExpectedOutput,
		&i.Metadata,
		&i.SourceTraceID,
		&i.CreatedAt,
	)
	return i, err
}

const getDatasetItemsByDatasetID = `-- name: GetDatasetItemsByDatasetID :many
SELECT id, dataset_id, input, expected_output, metadata, source_trace_id, created_at FROM dataset_items WHERE dataset_id = $1 ORDER BY created_at
`

func (q *Queries) GetDatasetItemsByDatasetID(ctx context.Context, datasetID string) ([]DatasetItem, error) {
	rows, err := q.db.Query(ctx, getDatasetItemsByDatasetID, datasetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatasetItem{}
	for rows.Next() {
		var i DatasetItem
		if err := rows.Scan(
			&i.ID,
			&i.DatasetID,
			&i.Input,
			&i.ExpectedOutput,
			&i.Metadata,
			&i.SourceTraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatasetRunByID = `-- name: GetDatasetRunByID :one
SELECT id, dataset_id, name, created_at FROM dataset_runs WHERE id = $1
`

func (q *Queries) GetDatasetRunByID(ctx context.Context, id string) (DatasetRun, error) {
	row := q.db.QueryRow(ctx, getDatasetRunByID, id)
	var i DatasetRun
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getDatasetRunItemByID = `-- name: GetDatasetRunItemByID :one
SELECT id, dataset_run_id, dataset_item_id, observation_id, score_id, created_at FROM dataset_run_items WHERE id = $1
`

func (q *Queries) GetDatasetRunItemByID(ctx context.Context, id string) (DatasetRunItem, error) {
	row := q.db.QueryRow(ctx, getDatasetRunItemByID, id)
	var i DatasetRunItem
	err := row.Scan(
		&i.ID,
		&i.DatasetRunID,
		&i.DatasetItemID,
		&i.ObservationID,
		&i.ScoreID,
		&i.CreatedAt,
	)
	return i, err
}

const getDatasetRunItemsByRunID = `-- name: GetDatasetRunItemsByRunID :many
SELECT id, dataset_run_id, dataset_item_id, observation_id, score_id, created_at FROM dataset_run_items WHERE dataset_run_id = $1 ORDER BY created_at
`

func (q *Queries) GetDatasetRunItemsByRunID(ctx context.Context, datasetRunID string) ([]DatasetRunItem, error) {
	rows, err := q.db.Query(ctx, getDatasetRunItemsByRunID, datasetRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatasetRunItem{}
	for rows.Next() {
		var i DatasetRunItem
		if err := rows.Scan(
			&i.ID,
			&i.DatasetRunID,
			&i.DatasetItemID,
			&i.ObservationID,
			&i.ScoreID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatasetRunsByDatasetID = `-- name: GetDatasetRunsByDatasetID :many
SELECT id, dataset_id, name, created_at FROM dataset_runs WHERE dataset_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetDatasetRunsByDatasetID(ctx context.Context, datasetID string) ([]DatasetRun, error) {
	rows, err := q.db.Query(ctx, getDatasetRunsByDatasetID, datasetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatasetRun{}
	for rows.Next() {
		var i DatasetRun
		if err := rows.Scan(
			&i.ID,
			&i.DatasetID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatasetsByProjectID = `-- name: GetDatasetsByProjectID :many
SELECT id, project_id, name, description, created_at FROM datasets WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetDatasetsByProjectID(ctx context.Context, projectID string) ([]Dataset, error) {
	rows, err := q.db.Query(ctx, getDatasetsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dataset{}
	for rows.Next() {
		var i Dataset
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberByUserAndOrg = `-- name: GetMemberByUserAndOrg :one
SELECT id, user_id, org_id, role FROM members WHERE user_id = $1 AND org_id = $2
`

type GetMemberByUserAndOrgParams struct {
	UserID string `db:"user_id" json:"user_id"`
	OrgID  string `db:"org_id" json:"org_id"`
}

func (q *Queries) GetMemberByUserAndOrg(ctx context.Context, arg GetMemberByUserAndOrgParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByUserAndOrg, arg.UserID, arg.OrgID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Role,
	)
	return i, err
}

const getObservationByID = `-- name: GetObservationByID :one
SELECT id, trace_id, type, name, input, output, metadata, model, model_parameters, start_time, end_time, token_usage, cost, status, parent_observation_id FROM observations WHERE id = $1
`

func (q *Queries) GetObservationByID(ctx context.Context, id string) (Observation, error) {
	row := q.db.QueryRow(ctx, getObservationByID, id)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.Type,
		&i.Name,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.Model,
		&i.ModelParameters,
		&i.StartTime,
		&i.EndTime,
		&i.TokenUsage,
		&i.Cost,
		&i.Status,
		&i.ParentObservationID,
	)
	return i, err
}

const getObservationsByTraceID = `-- name: GetObservationsByTraceID :many
SELECT id, trace_id, type, name, input, output, metadata, model, model_parameters, start_time, end_time, token_usage, cost, status, parent_observation_id FROM observations 
WHERE trace_id = $1 
ORDER BY start_time ASC
`

func (q *Queries) GetObservationsByTraceID(ctx context.Context, traceID string) ([]Observation, error) {
	rows, err := q.db.Query(ctx, getObservationsByTraceID, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Observation{}
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.Type,
			&i.Name,
			&i.Input,
			&i.Output,
			&i.Metadata,
			&i.Model,
			&i.ModelParameters,
			&i.StartTime,
			&i.EndTime,
			&i.TokenUsage,
			&i.Cost,
			&i.Status,
			&i.ParentObservationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, created_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, org_id, created_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrgID,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectsByOrgID = `-- name: GetProjectsByOrgID :many
SELECT id, name, org_id, created_at FROM projects WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetProjectsByOrgID(ctx context.Context, orgID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByOrgID, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrgID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPromptByID = `-- name: GetPromptByID :one
SELECT id, project_id, name, version, prompt, config, is_active, created_at FROM prompts WHERE id = $1
`

func (q *Queries) GetPromptByID(ctx context.Context, id string) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPromptByID, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.Prompt,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptByNameAndVersion = `-- name: GetPromptByNameAndVersion :one
SELECT id, project_id, name, version, prompt, config, is_active, created_at FROM prompts WHERE project_id = $1 AND name = $2 AND version = $3
`

type GetPromptByNameAndVersionParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Name      string `db:"name" json:"name"`
	Version   int32  `db:"version" json:"version"`
}

func (q *Queries) GetPromptByNameAndVersion(ctx context.Context, arg GetPromptByNameAndVersionParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPromptByNameAndVersion, arg.ProjectID, arg.Name, arg.Version)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Version,
		&i.Prompt,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptsByProjectID = `-- name: GetPromptsByProjectID :many
SELECT id, project_id, name, version, prompt, config, is_active, created_at FROM prompts 
WHERE project_id = $1 
ORDER BY name, version DESC
`

func (q *Queries) GetPromptsByProjectID(ctx context.Context, projectID string) ([]Prompt, error) {
	rows, err := q.db.Query(ctx, getPromptsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prompt{}
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Version,
			&i.Prompt,
			&i.Config,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScoreByID = `-- name: GetScoreByID :one
SELECT id, trace_id, name, value, comment, source, user_id, created_at FROM scores WHERE id = $1
`

func (q *Queries) GetScoreByID(ctx context.Context, id string) (Score, error) {
	row := q.db.QueryRow(ctx, getScoreByID, id)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.Name,
		&i.Value,
		&i.Comment,
		&i.Source,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getScoresByTraceID = `-- name: GetScoresByTraceID :many
SELECT id, trace_id, name, value, comment, source, user_id, created_at FROM scores WHERE trace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetScoresByTraceID(ctx context.Context, traceID string) ([]Score, error) {
	rows, err := q.db.Query(ctx, getScoresByTraceID, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Score{}
	for rows.Next() {
		var i Score
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.Name,
			&i.Value,
			&i.Comment,
			&i.Source,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTraceByID = `-- name: GetTraceByID :one
SELECT id, project_id, name, input, output, metadata, user_id, session_id, tags, start_time, end_time, total_cost, token_usage, created_at FROM traces WHERE id = $1
`

func (q *Queries) GetTraceByID(ctx context.Context, id string) (Trace, error) {
	row := q.db.QueryRow(ctx, getTraceByID, id)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.UserID,
		&i.SessionID,
		&i.Tags,
		&i.StartTime,
		&i.EndTime,
		&i.TotalCost,
		&i.TokenUsage,
		&i.CreatedAt,
	)
	return i, err
}

const getTracesByProjectID = `-- name: GetTracesByProjectID :many
SELECT id, project_id, name, input, output, metadata, user_id, session_id, tags, start_time, end_time, total_cost, token_usage, created_at FROM traces 
WHERE project_id = $1 
ORDER BY start_time DESC
LIMIT $2 OFFSET $3
`

type GetTracesByProjectIDParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Limit     int32  `db:"limit" json:"limit"`
	Offset    int32  `db:"offset" json:"offset"`
}

func (q *Queries) GetTracesByProjectID(ctx context.Context, arg GetTracesByProjectIDParams) ([]Trace, error) {
	rows, err := q.db.Query(ctx, getTracesByProjectID, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trace{}
	for rows.Next() {
		var i Trace
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Input,
			&i.Output,
			&i.Metadata,
			&i.UserID,
			&i.SessionID,
			&i.Tags,
			&i.StartTime,
			&i.EndTime,
			&i.TotalCost,
			&i.TokenUsage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, email, password_hash, name, created_at FROM users WHERE id = $1
`

// queries.sql
// Type-safe SQL queries for sqlc
func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const updatePromptActive = `-- name: UpdatePromptActive :exec
UPDATE prompts SET is_active = $3 WHERE project_id = $1 AND name = $2
`

type UpdatePromptActiveParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Name      string `db:"name" json:"name"`
	IsActive  bool   `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdatePromptActive(ctx context.Context, arg UpdatePromptActiveParams) error {
	_, err := q.db.Exec(ctx, updatePromptActive, arg.ProjectID, arg.Name, arg.IsActive)
	return err
}

const updateTrace = `-- name: UpdateTrace :one
UPDATE traces
SET name = COALESCE($2, name),
    input = COALESCE($3, input),
    output = COALESCE($4, output),
    metadata = COALESCE($5, metadata),
    end_time = COALESCE($6, end_time),
    total_cost = COALESCE($7, total_cost),
    token_usage = COALESCE($8, token_usage)
WHERE id = $1
RETURNING id, project_id, name, input, output, metadata, user_id, session_id, tags, start_time, end_time, total_cost, token_usage, created_at
`

type UpdateTraceParams struct {
	ID         string             `db:"id" json:"id"`
	Name       pgtype.Text        `db:"name" json:"name"`
	Input      []byte             `db:"input" json:"input"`
	Output     []byte             `db:"output" json:"output"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	EndTime    pgtype.Timestamptz `db:"end_time" json:"end_time"`
	TotalCost  pgtype.Float8      `db:"total_cost" json:"total_cost"`
	TokenUsage []byte             `db:"token_usage" json:"token_usage"`
}

func (q *Queries) UpdateTrace(ctx context.Context, arg UpdateTraceParams) (Trace, error) {
	row := q.db.QueryRow(ctx, updateTrace,
		arg.ID,
		arg.Name,
		arg.Input,
		arg.Output,
		arg.Metadata,
		arg.EndTime,
		arg.TotalCost,
		arg.TokenUsage,
	)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.UserID,
		&i.SessionID,
		&i.Tags,
		&i.StartTime,
		&i.EndTime,
		&i.TotalCost,
		&i.TokenUsage,
		&i.CreatedAt,
	)
	return i, err
}
